CREATE TABLE IF NOT EXISTS File_Data(
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    hash TEXT,
    data_oid OID NOT NULL
);

CREATE TABLE IF NOT EXISTS Files(
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    size BIGINT NOT NULL,
    modtime timestamptz NOT NULL,
    isdirectory BOOLEAN NOT NULL,
    parentid INT NOT NULL,
    file_data_id INT NOT NULL,
    path TEXT,
    FOREIGN KEY (file_data_id) REFERENCES File_Data(id)
        ON DELETE CASCADE
);

INSERT INTO File_Data(data_oid) VALUES(1);
INSERT INTO Files(name, size, modtime, isdirectory, parentid, file_data_id) VALUES ('root', 0, now(), true, 0, 1);