version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-fs
    restart: always
    env_file:
      - .env
    ports:
      - '5436:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      net:
        ipv4_address: 192.168.1.20
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-fs
    ports:
      - '8080:8080'
    depends_on:
      - postgres-db
    volumes:
      - .:/app
    networks:
      net:
        ipv4_address: 192.168.1.10

volumes:
  postgres-db:
    driver: local

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.67/24
